const keyboardKeys = [
  { value: "Q" },
  { value: "W" },
  { value: "E" },
  { value: "R" },
  { value: "T" },
  { value: "Y" },
  { value: "U" },
  { value: "I" },
  { value: "O" },
  { value: "P" },
  { value: "A" },
  { value: "S" },
  { value: "D" },
  { value: "F" },
  { value: "G" },
  { value: "H" },
  { value: "J" },
  { value: "K" },
  { value: "L" },
  { value: "Ñ" },
  { value: "=>" },
  { value: "Z" },
  { value: "X" },
  { value: "C" },
  { value: "V" },
  { value: "B" },
  { value: "N" },
  { value: "M" },
  { value: "<-" }
];

export default keyboardKeys;
